version: "3.1"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - django
  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "8001:3000"
    volumes:
      - ./node-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start:dev"]

  php:
    image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-app:/app
    ports:
      - "8002:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  django:
    image: python:3.9-slim
    working_dir: /usr/src/app
    volumes:
      - ./django-app:/usr/src/app
    ports:
      - "8003:8000"
    command: >
      /bin/sh -c "
        pip install --no-cache-dir django &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      PYTHONUNBUFFERED: 1